export const navLinks = [
  { label: "理念", href: "#philosophy" },
  { label: "怎么记", href: "#record" },
  { label: "遇见自己", href: "#meet" },
  { label: "回响", href: "#echo" },
] as const;

export type Facet = { label: string; value: string; size: number; left: string; top: string };

export const content = {
  nav: { brand: "念念", cta: "预约内测" },
  hero: {
    eyebrow: "念念 Memo",
    tagline: "情绪日记 · AI 分身",
    title: "记录情绪，遇见自己",
    sub: ["把心里的话放进来——一句、一段语音、一张照片都好。", "它一直在听，慢慢拼出另一个你。"],
    primary: "了解念念",
    ghost: "预约内测",
  },
  philosophy: {
    eyebrow: "关于念念",
    title: ["情绪不需要被打分，", "只需要被接住。"],
    body: "市面上的日记总想把你变成数据——打分、打卡、连续记录第几天。念念不这样。它不替你计算，只是认真听；被接住的那一刻，事情就已经轻了一点。",
    pillars: [
      { num: "01", h: "它不催你", p: "没有连续打卡，没有红点提醒。想说的时候再来，隔很久也没关系。" },
      { num: "02", h: "它不评判你", p: "不分析、不说教、不下结论。你说什么都不会被纠正，也不会被记成缺点。" },
      { num: "03", h: "它只对你一个人", p: "你写下的不公开、不推荐、不被比较。这里只有你和它。" },
    ],
  },
  record: {
    eyebrow: "怎么记",
    title: ["想怎么说，", "就怎么说。"],
    body: "打字、语音、拍张照、录段视频都行。不用写得完整，也不用每天都来。哪怕只是一句「今天好累」，它也会替你收好。",
    writingLine: "今天好累，但好像也没什么大事。",
    modes: ["文字", "语音", "照片", "视频"],
  },
  companion: {
    eyebrow: "你的分身",
    title: ["你说的每一句，", "它都接得住。"],
    body: "念念会为你养一个分身。你写下情绪，它会轻轻回一句——不评价，不急着安慰，只是让你知道：有人听见了。",
    response: ["累就先歇着，", "这一天我替你记着。"],
  },
  meetYourself: {
    eyebrow: "遇见自己",
    title: ["记着记着，", "你会慢慢认出自己。"],
    body: "每一次记录都在替你显影：性格、喜好、在意的人、说不出口的情绪……它们像一颗颗轻轻浮起的光，慢慢聚成你的轮廓。",
    facets: [
      { label: "性格", value: "温和", size: 130, left: "4%", top: "96px" },
      { label: "心理画像", value: "INFJ", size: 158, left: "28%", top: "8px" },
      { label: "人际关系", value: "亲密朋友 5 人", size: 120, left: "55%", top: "128px" },
      { label: "职业身份", value: "产品设计师", size: 142, left: "74%", top: "24px" },
      { label: "喜好", value: "阅读", size: 108, left: "40%", top: "212px" },
      { label: "生活节奏", value: "周末独处", size: 96, left: "66%", top: "236px" },
    ] as Facet[],
  },
  cloud: {
    eyebrow: "云游",
    title: ["你的分身，", "替你去遇见另一个 ta。"],
    body: "记着记着，这个分身就长成了你的模样。它带着你的心事，在念念的世界里走一走，遇见另一个有相似故事的人——然后你发现，那种安静，并不是孤独。",
    encounter: { who: "夜里也常醒着的人", sub: "另一个 ta", theme: "深夜独处的松弛", quote: "「那种安静，不是孤独」" },
  },
  echo: {
    eyebrow: "回响",
    title: ["每隔一阵，", "它会写一封信给你。"],
    body: "念念把你这段时间留下的话，轻轻收成一封回响——不是报告，也不是建议，更像一个老朋友在月底对你说：这段日子，辛苦了。",
    letterMeta: "回响 · 三月",
    letterExcerpt: ["这个月你说得最多的是「累」，", "但也有三次，你说还好撑过来了。"],
  },
  privacy: {
    eyebrow: "只属于你",
    title: ["这里没有别人，", "只有你和它。"],
    body: "你写下的一切都只为你保存——不公开、不推荐、不拿去比较。隐私是念念的底线，不是一个功能点。",
  },
  closing: {
    manifesto: ["它不替你下结论，也不急着把你变好。", "它只是一直在这儿，", "等你愿意开口的那一刻。"],
    cta: "预约内测",
    note: "内测就快开始了，留个邮箱，第一时间叫你。",
  },
  dashboard: {
    metadataTitle: "念念的健康报告",
    eyebrow: "NIANNIAN PRODUCT HEALTH",
    title: "念念的健康报告",
    description: "分开看持续使用、新用户与留存、累计规模、记录活跃。",
    allHistory: "全部历史",
    last7Days: "近 7 天",
    last30Days: "近 30 天",
    thisMonth: "本月",
    customRange: "自定义",
    overviewRange: "新用户与累计区间",
    from: "开始日期",
    to: "结束日期",
    apply: "应用筛选",
    sustainedUsageTitle: "持续使用",
    sustainedUsageDescription: "截至昨天，以每天向前滚动 28 个完整自然日的方式观察持续记录用户、变化和使用深度。",
    continuous28DayUsers: "28 日持续记录用户数",
    continuousUserRate: "持续记录用户率",
    newContinuousUsers: "新增持续用户",
    exitedContinuousUsers: "退出持续用户",
    continuousMovementDetail: "相比前一个统计日",
    continuousUserMessages: "持续记录用户总消息",
    continuousUserMessagesDetail: "统计 28 日持续记录用户在当前 28 日窗口内的有效消息",
    averageMessagesPerContinuousUser: "持续记录用户人均每天发送消息",
    sustainedTrendTitle: "28 日持续记录滚动趋势",
    sustainedTrendDescription: "每天向前滚动 28 个完整自然日计算；折线为持续用户数，悬停或使用方向键查看用户率及新增、退出人数。",
    sustainedUsageUnavailable: "等待刷新真实数据快照",
    dailyMessageUnit: "条 / 人 / 天",
    newUserTitle: "新用户",
    newUserDescription: "按注册日期选择用户批次；当日激活与 D0 行为观察注册当天，7 日激活仅纳入已完成 7 天观察的用户。",
    newUserMessages: "新用户 D0 消息",
    newUserDailyEchoes: "新用户 D0 日回响",
    newUserHighlightImages: "新用户 D0 此刻生图",
    averageMessagesPerNewUser: "人均",
    behaviorTrendTitle: "新用户行为趋势",
    behaviorTrendDescription: "上方三条线共用“人数 / 生成数”刻度，下方消息柱使用独立刻度；悬停或方向键查看当天精确值。",
    cohortDataUnavailable: "等待刷新真实数据快照",
    cumulativeTitle: "累计规模",
    cumulativeDescription: "累计注册展示区间开始前与区间结束时的规模变化；消息、此刻与日回响统计所选区间。",
    registeredUsers: "累计注册用户数",
    newUsers: "新用户数",
    messages: "累计消息条数",
    highlightImages: "累计此刻生图数",
    dailyEchoes: "累计日回响生成数",
    messageTypes: { text: "文字", image: "图片", voice: "语音", video: "视频" },
    healthTitle: "记录活跃",
    healthDescription: "当日、当周和趋势各自选择时间，三者互不联动。",
    sameDayActivation: "新用户当日激活率",
    sevenDayActivation: "新用户 7 日激活率",
    activityGroupTitle: "当日状态",
    activityGroupDescription: "只看所选观察日当天的记录用户数。",
    weeklyGroupTitle: "当周习惯",
    retentionTitle: "新用户留存分析",
    retentionDescription: "选择一个注册日，观察当天完成首次记录的新用户在已经发生的 D1–D30 每个自然日是否回来记录。",
    observationDate: "观察日",
    selectObservationDate: "选择观察日",
    observationDateHint: "选择某一天，查看当天的记录活跃状态。",
    latestObservationDate: "回到最新日",
    statisticWeek: "统计周",
    selectStatisticWeek: "选择统计周",
    statisticWeekHint: "点击任意日期，选择它所在的北京时间自然周。",
    latestStatisticWeek: "回到当前周",
    trendRange: "趋势日期范围",
    selectTrendRange: "选择趋势日期范围",
    trendRangeHint: "只控制下方的活跃与记录趋势，不影响当日、当周以及新用户与累计数据。",
    allTrendHistory: "全部历史趋势",
    clearTrendRange: "恢复全部趋势",
    recordDau: "当日 DAU",
    recordWau: "当周 WAU",
    weeklyEffectiveUsers: "当周有效记录用户数",
    weeklyAverageRecordDays: "当周人均记录天数",
    numeratorDenominator: "{numerator}/{denominator} 人",
    dayUnit: "天",
    trendTitle: "活跃与记录趋势",
    trendDescription: "记录用户与消息按北京时间自然日统计；使用右侧时间控件单独筛选，悬停或使用方向键查看每天的精确数据。",
    activeUsers: "记录用户",
    registrations: "新用户",
    messageVolume: "消息",
    viewDailyDetail: "查看最近每日明细",
    date: "日期",
    dateRange: "日期范围",
    selectDateRange: "选择日期范围",
    dateRangeHint: "选择开始与结束日期",
    selectEndDate: "已选开始日期，请继续选择结束日期",
    clearRange: "恢复全部历史",
    previousMonth: "上一个月",
    nextMonth: "下一个月",
    calendarWeekdays: ["一", "二", "三", "四", "五", "六", "日"],
    hoverHint: "悬停或使用左右方向键查看每日数据",
    metricDefinitions: {
      "28 日持续记录用户数": "截至昨天，过去 28 个完整北京时间自然日内至少 24 天有效记录、任意连续 3 天至少记录 1 天，且最近 2 天至少记录 1 天的去重用户数。",
      "持续记录用户率": "28 日持续记录用户数 ÷ 过去 28 天有过有效记录、且截至统计日已经注册满 28 天的用户数。",
      "新增持续用户": "当前统计日符合 28 日持续记录标准、但前一个统计日不符合的去重用户数。",
      "退出持续用户": "前一个统计日符合 28 日持续记录标准、但当前统计日不再符合的去重用户数。",
      "持续记录用户总消息": "当前 28 日持续记录用户在同一 28 日窗口内成功落库的文字、图片、语音和视频消息总数；不包含 AI 回复。",
      "持续记录用户人均每天发送消息": "当前 28 日持续记录用户在同一窗口内的有效消息总数 ÷ 持续记录用户数 ÷ 28 个自然日。",
      "新用户数": "注册时间落在新用户模块所选区间内的用户数，按北京时间自然日统计。",
      "新用户当日激活率": "新注册用户中，在注册当天北京时间 24:00 前至少完成一次有效记录的用户占比。",
      "新用户 7 日激活率": "已完整观察 7 天的新用户中，在注册日起 D0—D6 至少有 2 个不同自然日完成有效记录的用户占比。",
      "新用户 D0 消息": "新用户模块所选注册批次的用户，在注册当天成功落库的文字、图片、语音和视频消息数；不包含 AI 回复。",
      "新用户 D0 日回响": "新用户模块所选注册批次的用户，对应注册当天已持久化的日回响数。",
      "新用户 D0 此刻生图": "新用户模块所选注册批次的用户，在注册当天发起且最终成功并保存结果图的“此刻”生成任务数。",
      "累计注册用户数": "全历史时展示截至筛选结束日的累计注册人数；选择区间时展示区间开始前累计、区间结束日累计及净增。",
      "累计消息条数": "新用户模块所选区间内成功落库的用户消息行数，并按文字、图片、语音、视频拆分；不包含 AI 回复。",
      "累计此刻生图数": "新用户模块所选区间内状态为成功且已经保存结果图的“此刻”生成任务数。",
      "累计日回响生成数": "新用户模块所选区间内已持久化的唯一用户日回响数；同一用户同一天重跑覆盖不重复累计。",
      "当日 DAU": "所选观察日当天至少完成一次有效记录的去重用户数。",
      "当周 WAU": "所选统计周内至少完成一次有效记录的去重用户数；当前周只统计到快照截止日。",
      "当周有效记录用户数": "所选统计周内至少在 2 个不同北京时间自然日完成有效记录的去重用户数。",
      "当周人均记录天数": "所选统计周的有效记录用户总人天 ÷ 当周 WAU；同一用户同一天只计 1 人天。"
    },
    queriedAt: "查询时间",
    snapshotAt: "快照截止时间",
    rangeLabel: "数据范围",
    timezone: "北京时间",
    loading: "正在整理产品数据…",
    configurationTitle: "看板数据源尚未配置",
    configurationBody: "请配置后端地址与看板访问密钥后刷新页面。",
    retryTitle: "暂时无法读取产品数据",
    retryBody: "数据没有被修改，可以稍后刷新重试。",
    mockBadge: "本地示例数据",
    snapshotBadge: "生产数据快照",
    currentWeek: "当前统计周",
    asOf: "截至",
    noData: "当前范围暂无数据",
  },
  footer: { brand: "念念 Memo · 2026", tags: ["隐私优先", "不打分", "只为你写"] },
} as const;
